### ISSUE TITLE
Error-Code: 106-0502

### ISSUE THREAD

**Issue by leuldereje** [SmmServer/SmmServer#5]
I get the above error code when I try to open the course world

NEX (SMM)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/3847995/NEX.SMM.log)

NEX (Friends)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/3847997/NEX.Friends.log)

Caddy
[Caddy.log](https://github.com/SmmServer/SmmServer/files/3847999/Caddy.log)

**Comment by mrexodia** [comment]
There is an error with Caddy (the web server):

2019/11/14 10:09:30 Listen: listen tcp :80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

This probably means you don't have enough permissions (try running SmmServer as admin), or there is already a webserver running on your machine.

**Comment by leuldereje** [comment]
Runing as Admin didn't work.

"there is already a webserver running on your machine."
how can I check this? @mrexodia

**Comment by mrexodia** [comment]
Run [CurrPorts](http://www.nirsoft.net/utils/cports.zip) and save the HTML report for all items:

![](https://i.imgur.com/6FeVnN9.png)

If you are not comfortable with sharing, sort by `Local port` and see if you can find any entry with 80 or 443 there, it could look something like this:

![](https://i.imgur.com/Y0oxLLy.png)

It could also be that you have to whitelist `caddy.exe` in your firewall (you can temporarily disable your firewall completely and see if the error goes away to test this).

**Comment by leuldereje** [comment]
this is what I got 


![Capture](https://user-images.githubusercontent.com/18234761/68988133-97922a80-07e7-11ea-8f74-f080ef3a3924.PNG)

**Comment by mrexodia** [comment]
For VMWare: https://communities.vmware.com/thread/547810

For SYSTEM using port 80 I have no idea where this is coming from and you might have to investigate a bit more by yourself.

**Comment by leuldereje** [comment]
I fixed port 80 by System using  
https://stackoverflow.com/questions/1430141/port-80-is-being-used-by-system-pid-4-what-is-that

but the problem is still there

**NEX (smmdb)**

    [2019-11-16 08:39:36] INFO: [smmdb] nothing to do for Difficulty.Easy
    [2019-11-16 08:39:36] INFO: [smmdb] nothing to do for Difficulty.Normal
    [2019-11-16 08:39:37] INFO: [smmdb] nothing to do for Difficulty.Expert
    [2019-11-16 08:39:37] INFO: [smmdb] nothing to do for Difficulty.SuperExpert
    [2019-11-16 08:39:37] INFO: Starting PRUDP server at 127.0.0.1:59921:1
    [2019-11-16 08:39:37] INFO: smm secure server 127.0.0.1:59921
    [2019-11-16 08:39:37] INFO: Starting PRUDP server at 127.0.0.1:59900:1
    [2019-11-16 08:39:37] INFO: smm auth server 127.0.0.1:59900
    Traceback (most recent call last):
      File "C:\Users\Temporary\Desktop\SmmServerFinal_v5\SmmServerFinal\NintendoClients\example_smm_server.py", line 631, in <module>
    main()
      File "C:\Users\Temporary\Desktop\SmmServerFinal_v5\SmmServerFinal\NintendoClients\example_smm_server.py", line 627, in main
    input("Press enter to exit...\n")
    RuntimeError: input(): lost sys.stdin

**NEX (Friends)**

     [2019-11-16 08:43:53] INFO: Starting PRUDP server at 127.0.0.1:60021:1
     [2019-11-16 08:43:53] INFO: friends secure server 127.0.0.1:60021
     [2019-11-16 08:43:53] INFO: Starting PRUDP server at 127.0.0.1:60000:1
     [2019-11-16 08:43:53] INFO: friends auth server 127.0.0.1:60000
     Traceback (most recent call last):
     File "C:\Users\Temporary\Desktop\SmmServerFinal_v5\SmmServerFinal\NintendoClients\example_friend_server.py", line 199, in <module>
    main()
      File "C:\Users\Temporary\Desktop\SmmServerFinal_v5\SmmServerFinal\NintendoClients\example_friend_server.py", line 195, in main
    input("Press enter to exit...\n")
    RuntimeError: input(): lost sys.stdin

**Caddy**

    Activating privacy features... done.

    Serving HTTP on port 80 
    http://account.nintendo.net
    http://wup-ama.app.nintendo.net

    Serving HTTPS on port 443 
    https://account.nintendo.net
    https://wup-ama.app.nintendo.net


![Capture](https://user-images.githubusercontent.com/18234761/68996394-28035600-084e-11ea-8224-afc252c9628c.PNG)


**Note:** I posted all the log here because all the log file was empty, only displayed in the smmserver application

**Comment by mrexodia** [comment]
The first problem has now been solved, but you are encountering a different
issue now. Various users have reported this issue and I will make a fix for
it soon.

**Comment by mrexodia** [comment]
Download https://github.com/SmmServer/NintendoClients/archive/smm-server-public-v2.zip and copy the contents of the `NintendoClients-smm-server-public-v2` folder inside the `NintendoClients` folder and try again.

**Comment by leuldereje** [comment]
same error code but the log is different

**NEX (SMM)**

    [2019-11-16 11:50:22] INFO: [smmdb] nothing to do for Difficulty.Easy
    [2019-11-16 11:50:22] INFO: [smmdb] nothing to do for Difficulty.Normal
    [2019-11-16 11:50:22] INFO: [smmdb] nothing to do for Difficulty.Expert
    [2019-11-16 11:50:22] INFO: [smmdb] nothing to do for Difficulty.SuperExpert
    [2019-11-16 11:50:22] INFO: Starting PRUDP server at 127.0.0.1:59921:1
    [2019-11-16 11:50:22] INFO: smm secure server 127.0.0.1:59921
    [2019-11-16 11:50:22] INFO: Starting PRUDP server at 127.0.0.1:59900:1
    [2019-11-16 11:50:22] INFO: smm auth server 127.0.0.1:59900

**NEX (Friends)**

    [2019-11-16 11:50:20] INFO: Starting PRUDP server at 127.0.0.1:60021:1
    [2019-11-16 11:50:20] INFO: friends secure server 127.0.0.1:60021
    [2019-11-16 11:50:20] INFO: Starting PRUDP server at 127.0.0.1:60000:1
    [2019-11-16 11:50:20] INFO: friends auth server 127.0.0.1:60000

Caddy's log is the same as above
**Caddy**

    Activating privacy features... done.

    Serving HTTP on port 80 
    http://account.nintendo.net
    http://wup-ama.app.nintendo.net

    Serving HTTPS on port 443 
    https://account.nintendo.net
    https://wup-ama.app.nintendo.net

**Comment by mrexodia** [comment]
The server is now running without errors, but Cemu is not conneting there. Refer to https://github.com/SmmServer/SmmServer/issues/2 for various things you can try to fix it.

**Comment by mrexodia** [comment]
There has been an update to SmmServer. If you were previously experiencing issues that have not been fixed yet, download here: https://mega.nz/file/ykYXHKCR#E82kMeXW-Xxlh5VoQxU-izQ6UF5oLaPhMDM9sjzLAU8

Perform the following steps:

1. Open SmmServer
2. Click 'Start' to start the server
3. After a few seconds the 'Debug' button should become visible, press it
4. Wait for a while (~30 seconds)
5. Send all .log files
